### PR TITLE
Template based job creation

### PR DESCRIPTION
**Pull request by javiplx**
Adds capability of creating new projects for repositories with no job, using an existing Jenkins job as template, either using a single template for all unknown repositories or based on the repository name or group.

Although it doesn't merge automatically, I've cherry-picked the commits producing the conflicts and solved remaining ones, so it is safe to merge manually accepting changes from my branch (using -Xtheirs).

The only test I've not been able to fix is

    spec/values/project_spec.rb:113 # GitlabWebHook::Project when determining if matches repository url and branch when parametrized does not match when branch parameter is not of supported type

which produces a "only string parameters for branch parameter are supported" warning instead of the expected exception.

### CODE REVIEW

**Comment by javiplx** [comment]
Hello @elvanja, what are you going to do with this? As you said you're not currently using gitlab, you might not be comfortable by merging this. I understand that, and maybe it is just time to fork. I've also finished automatic project creation for merge requests, and contributing back to your repo is getting increasingly more difficult, because it relies on unmerged code.

**Comment by elvanja** [comment]
Hey @javiplx. Apologies for not responding sooner.

I'd like to have all this in the plugin but just can't find the time to merge the two code bases.
The problem is the your original refactor where I tried to merge to master but there is just to many collisions and things I just don't understand and I am having difficult time combining the two branches.

At the moment, I am almost prepared to let go of it all. If you'd like to take over this project, just let me know and I'll do it.

I guess the best thing would be to merge the code somehow, but since both of us can't find the time to do it, is seems there is going to be no progress. Sad but true.

If you have any suggestion on how to tackle this, I am listening.

**Comment by javiplx** [comment]
If you agree on passing the hat to me, I'm ready for that. In fact, I believe it is much better to keep on the same path, keeping on versioning with the same plugin name, because forking with a different name is just confusing.
I'll have a look at the Jenkins site, to check whether I need to do something for that, apart from having an account.

**Comment by elvanja** [comment]
Sure, I don't mind help of any kind :-) Anyway, I've release v1.2.0 to general public. It is missing features like merge request build and some other that remained open. Let me know how you want to proceed from here. I can even accept your code flat and just build and release it, whichever way you feel better with.

**Comment by javiplx** [comment]
I've just requested access to the jenkinsci fork of the repo. Don't mind about merging my code, I'll push it to the jenkins fork. If you prefer, I can do that 1.2.0 release, with the merges you've actually accepted on master plus this one (I must add the multiple_scm merge to my master, at least).

**Comment by elvanja** [comment]
1.2.0 is out already. But feel free to create a new release, maybe 2.0.0

**Comment by javiplx** [comment]
I didn't see the tag. I'll probably do the next release soon, but with less ambitious numbering than 2.0

**Comment by javiplx** [comment]
Already merged over 1.2.0 on my repo.

**Pull request closed without merging**
